const REQUEST_CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_REQUEST = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;
const DEFAULT = 500;
const DUPE_ERROR = 11000;

module.exports = {
  REQUEST_CREATED,
  BAD_REQUEST,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_REQUEST,
  NOT_FOUND,
  CONFLICT,
  DEFAULT,
  DUPE_ERROR,
};
